# Generated by Django 5.2.6 on 2025-09-22 14:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Farmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=15, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("district", models.CharField(max_length=50)),
                ("state", models.CharField(default="Kerala", max_length=50)),
                (
                    "preferred_language",
                    models.CharField(
                        choices=[("English", "English"), ("Malayalam", "Malayalam")],
                        default="English",
                        max_length=20,
                    ),
                ),
                ("experience_years", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KnowledgeBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "knowledge_type",
                    models.CharField(
                        choices=[
                            ("pest_control", "Pest Control"),
                            ("disease_management", "Disease Management"),
                            ("soil_management", "Soil Management"),
                            ("irrigation_tips", "Irrigation Tips"),
                            ("fertilizer_guide", "Fertilizer Guide"),
                            ("weather_advisory", "Weather Advisory"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "applicable_crops",
                    models.TextField(
                        help_text="Comma-separated list of applicable crops"
                    ),
                ),
                (
                    "applicable_regions",
                    models.TextField(
                        help_text="Comma-separated list of applicable districts/states"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CropCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crop_name", models.CharField(max_length=50)),
                ("district", models.CharField(max_length=50)),
                ("state", models.CharField(default="Kerala", max_length=50)),
                ("sowing_start_month", models.IntegerField()),
                ("sowing_end_month", models.IntegerField()),
                ("harvest_start_month", models.IntegerField()),
                ("harvest_end_month", models.IntegerField()),
                ("best_practices", models.TextField(blank=True)),
                (
                    "common_pests",
                    models.TextField(blank=True, help_text="JSON list of common pests"),
                ),
            ],
            options={
                "unique_together": {("crop_name", "district", "state")},
            },
        ),
        migrations.CreateModel(
            name="Farm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("district", models.CharField(max_length=50)),
                ("state", models.CharField(default="Kerala", max_length=50)),
                ("land_size_acres", models.FloatField()),
                (
                    "soil_type",
                    models.CharField(
                        choices=[
                            ("clay", "Clay"),
                            ("sandy", "Sandy"),
                            ("loamy", "Loamy"),
                            ("black", "Black Soil"),
                            ("red", "Red Soil"),
                            ("alluvial", "Alluvial"),
                            ("laterite", "Laterite"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "irrigation_type",
                    models.CharField(
                        choices=[
                            ("rain_fed", "Rain Fed"),
                            ("drip", "Drip Irrigation"),
                            ("sprinkler", "Sprinkler"),
                            ("flood", "Flood Irrigation"),
                            ("canal", "Canal"),
                            ("bore_well", "Bore Well"),
                            ("open_well", "Open Well"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "primary_crops",
                    models.TextField(help_text="Comma-separated list of crops"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="farms",
                        to="api.farmer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("sowing", "Sowing"),
                            ("irrigation", "Irrigation"),
                            ("fertilizer", "Fertilizer Application"),
                            ("pesticide", "Pesticide Application"),
                            ("weeding", "Weeding"),
                            ("harvesting", "Harvesting"),
                            ("pest_issue", "Pest Issue"),
                            ("disease_issue", "Disease Issue"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("text_note", models.TextField()),
                ("date", models.DateField(default=django.utils.timezone.now)),
                (
                    "amount",
                    models.FloatField(
                        blank=True, help_text="Quantity/amount if applicable", null=True
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        blank=True,
                        help_text="Type of input used (fertilizer name, etc.)",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="api.farm",
                    ),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="api.farmer",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("due_date", models.DateTimeField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("operation", "Farm Operation"),
                            ("scheme", "Government Scheme"),
                            ("price", "Price Alert"),
                            ("weather", "Weather Alert"),
                            ("pest", "Pest/Disease Alert"),
                            ("general", "General"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("is_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="api.farmer",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "-created_at"],
            },
        ),
    ]
